version: 2.1

jobs:
  test:
    docker:
      - image: thecodingmachine/php:8.1-v4-cli
    steps:
      - run: git clone -b ${CIRCLE_BRANCH} https://github.com/jonbaldie/functions.git && cd functions && composer install --ignore-platform-reqs --no-interaction && ./vendor/bin/phpunit ./tests --testdox && ./vendor/bin/phan --allow-polyfill-parser && ./vendor/bin/phpa ./src

workflows:
  test:
    jobs:
      - test
