version: 2.1

jobs:
  build:
    docker:
      - image: thecodingmachine/php:8.1-v4-cli
    steps:
      - run: git clone https://github.com/jonbaldie/functions.git && cd functions
      - run: composer install --ignore-platform-reqs --no-interaction

workflows:
  build_and_test:
    jobs:
      - build
